### PR TITLE
Merging latest changes to stable

### PR DESCRIPTION
**Pull request by SteveHNH**
Highlights

* If a post fails to post to inventory we consider that a failed payload
* System_profile make metadata fix for more than 64k 
* session.close() implemented for inventory posts

### CODE REVIEW

**Comment by SteveHNH** [comment]
@beav @wcmitchell 
Cherry-picking went a little sideways. Can you folks check to make sure your changes are in as expected? Had to resolve some conflicts along the way. I think I got it, but just want to be sure

**Comment by beav** [comment]
reviewing now

**Comment by beav** [comment]
I applied this patch and things worked for me

```patch
diff --git a/pup/utils/fact_extract.py b/pup/utils/fact_extract.py
index 1553b049..89a622ff 100644
--- a/pup/utils/fact_extract.py
+++ b/pup/utils/fact_extract.py
@@ -7,6 +7,8 @@ from insights.util.subproc import CalledProcessError
 
 from insights.core.archives import InvalidArchive
 from insights.parsers.dmidecode import DMIDecode
+from insights.parsers.cpuinfo import CpuInfo
+from insights.parsers.date import DateUTC
 from insights.parsers.installed_rpms import InstalledRpms
 from insights.parsers.lsmod import LsMod
 from insights.parsers.meminfo import MemInfo
@@ -14,14 +16,23 @@ from insights.parsers.redhat_release import RedhatRelease
 from insights.parsers.uname import Uname
 from insights.parsers.systemd.unitfiles import UnitFiles
 from insights.parsers.virt_what import VirtWhat
+from insights.parsers.ps import PsAuxcww
+from insights.parsers.ip import IpAddr
+from insights.parsers.uptime import Uptime
+from insights.parsers.yum_repos_d import YumReposD
 from insights.specs import Specs
-from insights.util.canonical_facts import get_canonical_facts, IPs
+from insights.util.canonical_facts import get_canonical_facts
+
 
 logger = logging.getLogger('advisor-pup')
 
 
-@rule(optional=[Specs.hostname, Specs.lscpu, VirtWhat, MemInfo, IPs, DMIDecode, RedhatRelease, Uname, LsMod, InstalledRpms, UnitFiles])
-def system_profile_facts(hostname, lscpu, virt_what, meminfo, ips, dmidecode, redhat_release, uname, lsmod, installed_rpms, unit_files):
+@rule(optional=[Specs.hostname, CpuInfo, VirtWhat, MemInfo, IpAddr, DMIDecode,
+                RedhatRelease, Uname, LsMod, InstalledRpms, UnitFiles, PsAuxcww,
+                DateUTC, Uptime, YumReposD])
+def system_profile(hostname, cpu_info, virt_what, meminfo, ip_addr, dmidecode,
+                   redhat_release, uname, lsmod, installed_rpms, unit_files, ps_auxcww,
+                   date_utc, uptime, yum_repos_d):
     """
     This method applies parsers to a host and returns a system profile that can
     be sent to inventory service.
@@ -101,6 +112,7 @@ def system_profile_facts(hostname, lscpu, virt_what, meminfo, ips, dmidecode, re
 
     metadata_response = make_metadata()
     profile_sans_none = _remove_empties(profile)
+    import pdb; pdb.set_trace()
     metadata_response.update(profile_sans_none)
     return metadata_response
 
@@ -126,52 +138,18 @@ def _get_virt_phys_fact(virt_what):
         return None
 
 
-def _create_services_fact(unit_files):
-    """
-    create a json serializable dict of services. The key is the service name,
-    and the value is if it's enabled or not.
-    """
-    services = {}
-    for service in unit_files.services:
-        if service.endswith('.service'):
-            services.update({service: unit_files.services[service]})
-
-    return services
-
-
-def test_ipv4_addr(address):
+def _enabled_services(unit_files):
     """
-    return true if address is ipv4, false otherwise
+    This method finds enabled services and strips the '.service' suffix
     """
-    try:
-        ipaddress.IPv4Address(address)
-        return True
-    except AddressValueError:
-        return False
+    return [service[:-8] for service in unit_files.services if unit_files.services[service] and '.service' in service]
 
 
-def test_ipv6_addr(address):
+def _installed_services(unit_files):
     """
-    return true if address is ipv6, false otherwise
+    This method finds installed services and strips the '.service' suffix
     """
-    try:
-        ipaddress.IPv6Address(address)
-        return True
-    except AddressValueError:
-        return False
-
-
-def ipv4_ipv6_addresses(addresses):
-    """
-    return a dict with IPv4 and IPv6 addresses
-    """
-    result = {'ipv4_addresses': [a for a in addresses if test_ipv4_addr(a)],
-              'ipv6_addresses': [a for a in addresses if test_ipv6_addr(a)]}
-    return result
-
-
-def bytes_to_gb(num_bytes):
-    return '%.1f' % float(num_bytes / 1_000_000_000) + " GB"
+    return [service[:-8] for service in unit_files.services if '.service' in service]
 
 
 # from insights-core get_canonical_facts util
@@ -197,9 +175,17 @@ def _remove_bad_display_name(facts):
     return defined_facts
 
 
-def get_system_profile_facts(path=None):
-    broker = run(system_profile_facts, root=path)
-    result = broker[system_profile_facts]
+def _remove_empties(d):
+    """
+    small helper method to remove keys with value of None, [] or ''. These are
+    not accepted by inventory service.
+    """
+    return {x: d[x] for x in d if d[x] not in [None, '', []]}
+
+
+def get_system_profile(path=None):
+    broker = run(system_profile, root=path)
+    result = broker[system_profile]
     del result["type"]  # drop metadata key
     return result
 
@@ -210,8 +196,9 @@ def extract_facts(archive):
     try:
         with extract(archive) as ex:
             facts = get_canonical_facts(path=ex.tmp_dir)
-            facts['system_profile'] = get_system_profile_facts(path=ex.tmp_dir)
+            facts['system_profile'] = get_system_profile(path=ex.tmp_dir)
     except (InvalidArchive, ModuleNotFoundError, KeyError, CalledProcessError) as e:
         facts['error'] = e.args[0]
 
-    return _strip_empty_facts(facts)
+    groomed_facts = _remove_empties(_remove_bad_display_name(facts))
+    return groomed_facts
diff --git a/tests/test_fact_extract.py b/tests/test_fact_extract.py
index 5eecb263..7a8b5591 100644
--- a/tests/test_fact_extract.py
+++ b/tests/test_fact_extract.py
@@ -5,16 +5,6 @@ from pup.utils import fact_extract
 
 class TestFormatHelpers(unittest.TestCase):
 
-    def test_bytes_to_gb(self):
-        gb = fact_extract.bytes_to_gb(987654321)
-        self.assertEquals(gb, "1.0 GB")
-
-    def test_ipv4_ipv6_addresses(self):
-        ip_addresses = ['8.8.8.8', '3ffe:1900:4545:3:200:f8ff:fe21:67cf']
-        result = fact_extract.ipv4_ipv6_addresses(ip_addresses)
-        self.assertIn('8.8.8.8', result['ipv4_addresses'])
-        self.assertIn('3ffe:1900:4545:3:200:f8ff:fe21:67cf', result['ipv6_addresses'])
-
     def test_strip_empty_facts(self):
         values = {"account": "12345", "metadata": {"display_name": "a", "empty_key": "", "non_empty_key": "non_empty_value"}}
         stripped_metadata = fact_extract._strip_empty_facts(values["metadata"])
```

**Comment by SteveHNH** [comment]
replacing this one with antoher

**Pull request closed without merging**
