### PR TITLE
break out consumer and producer from `pup.py`.

### PR DESCRIPTION
**Pull request by beav**
Previously, the kafka consumer and producer were in `pup.py`. This commit moves
them into ClientContext, a small class that also maintains the producer queue.

The consumer's methods have been moved to `consumer.py`.

Finally, `get_commit_date` was moved to `get_version_info`, which assembles the
dict that mnm needs.

### CODE REVIEW

**Comment by beav** [comment]
@SteveHNH this is the same as https://github.com/RedHatInsights/insights-pup/pull/42, I created this PR to get the jenkins tests to pass. The tests didn't seem to run from my local fork.

**Comment by beav** [comment]
rebase complete. a lot of code got moved around but it should not change functionality at all.

I went through the new PRs that were merged since the rebase and applied everything, so it should be current.

**Comment by beav** [comment]
@SteveHNH thx for the frosted flake8s :tiger:

**Comment by SteveHNH** [comment]
@beav no problem! going to do some testing and maybe rename a thing or two. I'd like to get this in because I know you've had it out here forever

**Comment by beav** [comment]
closing this out, will make a new refactor PR later

**Pull request closed without merging**
